spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost/micro
    username: postgres
    password: 44881212
  liquibase:
    change-log: classpath:db/changelog-master.xml
