spring:
  jackson:
    property-naming-strategy: SNAKE_CASE
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql:http://localhost/micro
    username: postgres
    password: 44881212