spring:
  jackson:
    property-naming-strategy: SNAKE_CASE
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost/micro
    username: postgres
    password: 44881212
  liquibase:
    change-log: classpath:db/changelog-master.xml

service:
  stock:
    url: http://localhost:8082